import React, { useEffect, useMemo, useState } from 'react';
import AppV16 from './AppV16.jsx';

const PACK_KEY = 'porchquest369.routePack.v7';
const API_KEY = 'porchquest369.apiBase';
const EMPTY = { schema: 'porchquest.route_pack.v1', id: 'empty-pack', title: 'Empty Pack', summary: '', quests: [], scenes: [], npcs: [], rewards: [], edges: [] };

function readPack() { try { return normalize(JSON.parse(localStorage.getItem(PACK_KEY) || '{}')); } catch { return EMPTY; } }
function normalize(raw) { const p = raw && typeof raw === 'object' ? raw : EMPTY; return { ...EMPTY, ...p, quests: Array.isArray(p.quests) ? p.quests : [], scenes: Array.isArray(p.scenes) ? p.scenes : [], npcs: Array.isArray(p.npcs) ? p.npcs : [], rewards: Array.isArray(p.rewards) ? p.rewards : [], edges: Array.isArray(p.edges) ? p.edges : [] }; }
function ids(list) { return new Set((list || []).map((item) => item.id).filter(Boolean)); }
function missing(current, base, key) { const a = ids(current[key]); const b = ids(base[key]); return { added: [...a].filter((id) => !b.has(id)), removed: [...b].filter((id) => !a.has(id)) }; }
function validation(pack) { const errors = []; const warnings = []; const q = ids(pack.quests); const s = ids(pack.scenes); if (pack.schema !== 'porchquest.route_pack.v1') errors.push('schema mismatch'); if (!/^[a-z0-9][a-z0-9_-]*$/.test(pack.id || '')) errors.push('pack id is not slug-safe'); if (!pack.quests.length) errors.push('at least one quest required'); if (!pack.scenes.length) errors.push('at least one scene required'); pack.scenes.forEach((x) => { if (!x.text) warnings.push(`scene ${x.id || 'new'} needs text`); if (x.quest_id && !q.has(x.quest_id)) warnings.push(`scene ${x.id || 'new'} links unknown quest`); }); pack.npcs.forEach((x) => { if (!x.clue) warnings.push(`npc ${x.id || 'new'} needs clue`); }); pack.rewards.forEach((x) => { if (!x.text) warnings.push(`reward ${x.id || 'new'} needs text`); }); pack.edges.forEach((x, i) => { if (!s.has(x.from) || !s.has(x.to)) warnings.push(`edge ${i + 1} links unknown scene`); }); return { errors, warnings, score: errors.length ? 'blocked' : warnings.length ? 'needs review' : 'ready' }; }
function promotion(pack, result) { const checks = [!result.errors.length, pack.scenes.length >= 2, pack.edges.length >= 1, pack.rewards.length >= 1, pack.npcs.every((n) => n.clue), pack.scenes.every((s) => s.text)]; const passed = checks.filter(Boolean).length; const total = checks.length; const label = result.errors.length ? 'blocked' : passed === total ? 'promotion ready' : passed >= 4 ? 'review pass' : 'draft'; return { label, passed, total, checks }; }
function localPackage(pack, result, promo) { const id = pack.id || 'route-pack'; const receipt = { schema: 'porchquest.pack_submission_receipt.v1', pack_id: id, title: pack.title, created_at: new Date().toISOString(), validation: result, promotion: promo, boundary: 'No secrets, private data, real-world targeting, or unsupported claims.' }; const checklist = [`# ${pack.title || id} Review`, '', '- [ ] Schema validation reviewed.', '- [ ] Safe fantasy/adventure content reviewed.', '- [ ] Playtest transcript reviewed.', '- [ ] Maintainer approval recorded.', ''].join('\n'); return { schema: 'porchquest.pack_submission_package.v1', pack_id: id, zip_name: `${id}.submission-package.zip`, files: [{ path: `content-packs/${id}.route-pack.json`, content: JSON.stringify(pack, null, 2) + '\n' }, { path: `content-packs/${id}.approval-receipt.json`, content: JSON.stringify(receipt, null, 2) + '\n' }, { path: `docs/reviews/${id}.md`, content: checklist }] }; }
function enc(s) { return new TextEncoder().encode(s); }
function u16(n) { return new Uint8Array([n & 255, (n >>> 8) & 255]); }
function u32(n) { return new Uint8Array([n & 255, (n >>> 8) & 255, (n >>> 16) & 255, (n >>> 24) & 255]); }
const CRC_TABLE = Array.from({ length: 256 }, (_, n) => { let c = n; for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1; return c >>> 0; });
function crc32(bytes) { let c = 0xffffffff; bytes.forEach((b) => { c = CRC_TABLE[(c ^ b) & 255] ^ (c >>> 8); }); return (c ^ 0xffffffff) >>> 0; }
function join(parts) { const size = parts.reduce((sum, p) => sum + p.length, 0); const out = new Uint8Array(size); let offset = 0; parts.forEach((p) => { out.set(p, offset); offset += p.length; }); return out; }
function zipBytes(files) { const locals = []; const centers = []; let offset = 0; const now = new Date(); const time = ((now.getHours() << 11) | (now.getMinutes() << 5) | Math.floor(now.getSeconds() / 2)) & 0xffff; const date = (((now.getFullYear() - 1980) << 9) | ((now.getMonth() + 1) << 5) | now.getDate()) & 0xffff; files.forEach((file) => { const name = enc(file.path); const data = enc(file.content || ''); const crc = crc32(data); const local = join([u32(0x04034b50), u16(20), u16(0), u16(0), u16(time), u16(date), u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), name, data]); const center = join([u32(0x02014b50), u16(20), u16(20), u16(0), u16(0), u16(time), u16(date), u32(crc), u32(data.length), u32(data.length), u16(name.length), u16(0), u16(0), u16(0), u16(0), u32(0), u32(offset), name]); locals.push(local); centers.push(center); offset += local.length; }); const central = join(centers); const end = join([u32(0x06054b50), u16(0), u16(0), u16(files.length), u16(files.length), u32(central.length), u32(offset), u16(0)]); return join([...locals, central, end]); }
function downloadZip(name, files) { const blob = new Blob([zipBytes(files)], { type: 'application/zip' }); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = name; a.click(); URL.revokeObjectURL(url); }

export default function AppV17() {
  const [pack, setPack] = useState(readPack);
  const [gallery, setGallery] = useState([]);
  const [base, setBase] = useState(null);
  const [baseId, setBaseId] = useState('');
  const [apiBase, setApiBase] = useState(localStorage.getItem(API_KEY) || 'http://127.0.0.1:8787');
  const [message, setMessage] = useState('Ready.');
  const result = useMemo(() => validation(pack), [pack]);
  const promo = useMemo(() => promotion(pack, result), [pack, result]);
  const diff = useMemo(() => base ? ['quests', 'scenes', 'npcs', 'rewards', 'edges'].map((key) => ({ key, ...missing(pack, normalize(base), key) })) : [], [pack, base]);
  useEffect(() => { fetch('content-packs/index.json').then((res) => res.json()).then((data) => setGallery(data.packs || [])).catch(() => setGallery([])); }, []);
  useEffect(() => { localStorage.setItem(API_KEY, apiBase); }, [apiBase]);
  function refresh() { setPack(readPack()); setMessage('Synced from full editor.'); }
  async function loadBase(id) { const entry = gallery.find((g) => g.id === id); setBaseId(id); if (!entry) return setBase(null); try { setBase(await fetch(entry.path).then((res) => res.json())); } catch { setBase(null); setMessage('Baseline load failed.'); } }
  function exportLocalZip() { const pkg = localPackage(pack, result, promo); downloadZip(pkg.zip_name, pkg.files); setMessage(`Downloaded ${pkg.zip_name}.`); }
  async function exportBackendZip() { try { const res = await fetch(`${apiBase.replace(/\/$/, '')}/api/content-packs/${encodeURIComponent(pack.id)}/submission-package`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ pack }) }); const data = await res.json(); if (!res.ok) throw new Error(data.detail || 'package failed'); const pkg = data.package; downloadZip(pkg.zip_name || `${pack.id}.submission-package.zip`, pkg.files || []); setMessage(`Downloaded backend package for ${pack.id}.`); } catch (error) { setMessage(`Backend zip failed: ${error.message}`); } }
  return <div className="app studio-v17">
    <header className="hero"><p className="eyebrow">PorchQuest369 v0.8.6</p><h1>Submission Packaging Console</h1><p className="subtle">State sync, zip export, promotion status, diff review, and gallery thumbnails.</p></header>
    <section className="panel v17-grid"><div><h2>{pack.title}</h2><p>{pack.summary || 'No summary.'}</p><p className={`status ${result.score === 'blocked' ? 'error' : result.score === 'ready' ? 'pass' : 'warning'}`}>{promo.label.toUpperCase()} · {promo.passed}/{promo.total} promotion checks</p><p className="subtle">{result.errors.length} errors · {result.warnings.length} warnings · {pack.scenes.length} scenes · {pack.edges.length} edges</p></div><div className="button-row"><button onClick={refresh}>Sync from Editor</button><button onClick={exportLocalZip}>Download Local Zip</button><button onClick={exportBackendZip}>Download Backend Zip</button></div></section>
    <section className="panel gallery"><h2>Reviewed Pack Gallery</h2><div className="gallery-grid">{gallery.map((entry) => <article className="gallery-card thumb-card" key={entry.id}><div className={`thumb thumb-${entry.thumbnail || 'pack'}`}>{entry.thumbnail || 'pack'}</div><h3>{entry.title}</h3><p>{entry.summary}</p><p className="subtle">{(entry.tags || []).join(' · ')} · {entry.status || 'reviewed'}</p><button onClick={() => loadBase(entry.id)}>Use as diff baseline</button></article>)}</div></section>
    <section className="panel"><h2>Content-Pack Diff Viewer</h2><label>Baseline<select value={baseId} onChange={(e) => loadBase(e.target.value)}><option value="">Choose reviewed pack</option>{gallery.map((entry) => <option key={entry.id} value={entry.id}>{entry.title}</option>)}</select></label>{base ? <div className="diff-grid">{diff.map((row) => <article className="diff-card" key={row.key}><h3>{row.key}</h3><p><b>Added:</b> {row.added.join(', ') || 'none'}</p><p><b>Removed:</b> {row.removed.join(', ') || 'none'}</p></article>)}</div> : <p className="subtle">Choose a reviewed pack to compare against the current editor pack.</p>}</section>
    <section className="panel backend-panel"><h2>Backend Zip Settings</h2><label>API Base<input value={apiBase} onChange={(e) => setApiBase(e.target.value)} /></label><p>{message}</p></section>
    <section className="panel"><h2>Full Editor</h2><p className="subtle">The full v0.8.5 studio remains below. Use Sync from Editor after edits to refresh this packaging console.</p></section>
    <AppV16 />
  </div>;
}
